# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math

def show_menu():
    print("----- Advanced Calculator -----")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Power")
    print("6. Modulus")
    print("7. Factorial")
    print("8. Square Root")
    print("9. Exit")

while True:
    show_menu()

    try:
        choice = int(input("Enter choice: "))

        # Exit condition
        if choice == 9:
            print("Program terminated")
            break

        # Operations with two numbers
        if choice in [1, 2, 3, 4, 5, 6]:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))

            if choice == 1:
                print("Result =", num1 + num2)

            elif choice == 2:
                print("Result =", num1 - num2)

            elif choice == 3:
                print("Result =", num1 * num2)

            elif choice == 4:
                if num2 == 0:
                    print("Cannot divide by zero.")
                else:
                    print("Result =", num1 / num2)

            elif choice == 5:
                print("Result =", num1 ** num2)

            elif choice == 6:
                print("Result =", num1 % num2)

        # Factorial
        elif choice == 7:
            num = int(input("Enter number: "))
            if num < 0:
                print("Negative factorial not allowed.")
            else:
                print("Factorial =", math.factorial(num))

        # Square Root
        elif choice == 8:
            num = float(input("Enter number: "))
            if num < 0:
                print("Cannot find square root of negative number.")
            else:
                print("Square Root =", math.sqrt(num))

        else:
            print("Invalid choice. Try again.")

    except ValueError:
        print("Invalid numeric input. Please enter numbers only.")

    print()   # For spacing