# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEM0bQOvhKBDmRW1kCLVyill8EFbsiTJ
"""

n = int(input("Enter number of temperature readings: "))

temperatures = []

# Step 3: Collect temperature values
for i in range(n):
    temp = float(input(f"Enter temperature {i+1}: "))
    temperatures.append(temp)

# Step 4: Calculate statistics
average_temp = sum(temperatures) / n
highest_temp = max(temperatures)
lowest_temp = min(temperatures)

# Step 5: Classification
hot_count = 0
cold_count = 0
normal_count = 0

for temp in temperatures:
    if temp < 18:
        cold_count += 1
    elif temp > 28:
        hot_count += 1
    else:
        normal_count += 1

# Step 6: Determine action
if hot_count > 0:
    action = "Fan ON"
elif cold_count > 0:
    action = "Heater ON"
else:
    action = "No Action Required"

# Step 7: Display summary
print("\n----- Temperature Summary Report -----")
print("Average Temperature:", round(average_temp, 2))
print("Highest Temperature:", highest_temp)
print("Lowest Temperature:", lowest_temp)
print("Hot Readings:", hot_count)
print("Normal Readings:", normal_count)
print("Cold Readings:", cold_count)
print("Suggested Action:", action)

# Step 8: End program
print("\nProgram Ended.")